// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForge.Data;

#nullable disable

namespace SkillForge.API.Migrations
{
    [DbContext(typeof(SkillForgeDbContext))]
    [Migration("20260801095337_SyncResumeRecruiterAndWorkflowSchema")]
    partial class SyncResumeRecruiterAndWorkflowSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateId");

                    b.HasIndex("ActiveResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateResume", b =>
                {
                    b.Property<int>("CandidateResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedResumeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateResumeId");

                    b.HasIndex("CandidateId", "FileName")
                        .IsUnique();

                    b.ToTable("CandidateResumes");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateShortlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyJobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContactRevealed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchExplanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectHiringRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CompanyJobRequestId");

                    b.HasIndex("ProjectHiringRequestId");

                    b.ToTable("CandidateShortlists");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.ToTable("CompanyJobRequests");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("ApplyUrl");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced C# Developer",
                            FetchedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalUrl = "",
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "C# Developer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            JobId = 2,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced React Developer",
                            FetchedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalUrl = "",
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "React Developer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            JobId = 3,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced DevOps Engineer",
                            FetchedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalUrl = "",
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "DevOps Engineer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            JobId = 4,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced Data Engineer",
                            FetchedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalUrl = "",
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "Data Engineer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            JobId = 5,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced Full Stack Developer",
                            FetchedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinalUrl = "",
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "Full Stack Developer",
                            WorkMode = "Hybrid"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.JobFetchHistory", b =>
                {
                    b.Property<int>("JobFetchHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSuccessfulFetchUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobFetchHistoryId");

                    b.ToTable("JobFetchHistories");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 12,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 13,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 21,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 22,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            Id = 23,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "CSS"
                        },
                        new
                        {
                            Id = 31,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = 32,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Kubernetes"
                        },
                        new
                        {
                            Id = 33,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Azure"
                        },
                        new
                        {
                            Id = 41,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "Python"
                        },
                        new
                        {
                            Id = 42,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 43,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "Spark"
                        },
                        new
                        {
                            Id = 51,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 52,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 53,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 54,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "Azure"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProjectDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TeamBreakdownApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamBreakdownJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.ToTable("ProjectHiringRequests");
                });

            modelBuilder.Entity("SkillForge.Models.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@skillforge.com",
                            PasswordHash = "$2a$11$6r2wEZVCp9v4EL0vPVA8uu7eYQ/qk4jZvJAqEYkLvyTlL6YsH8pf2",
                            Role = "Recruiter",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.HasOne("SkillForge.Models.CandidateResume", "ActiveResume")
                        .WithMany()
                        .HasForeignKey("ActiveResumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkillForge.Models.User", "User")
                        .WithMany("Candidates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActiveResume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateResume", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateShortlist", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillForge.Models.CompanyJobRequest", "CompanyJobRequest")
                        .WithMany("Shortlist")
                        .HasForeignKey("CompanyJobRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SkillForge.Models.ProjectHiringRequest", "ProjectHiringRequest")
                        .WithMany("Shortlist")
                        .HasForeignKey("ProjectHiringRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Candidate");

                    b.Navigation("CompanyJobRequest");

                    b.Navigation("ProjectHiringRequest");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.HasOne("SkillForge.Models.Recruiter", "Recruiter")
                        .WithMany("JobRequests")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany("JobMatches")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillForge.Models.Job", "Job")
                        .WithMany("Matches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Job", "Job")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.HasOne("SkillForge.Models.Recruiter", "Recruiter")
                        .WithMany("ProjectRequests")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.Navigation("Shortlist");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.Navigation("Shortlist");
                });

            modelBuilder.Entity("SkillForge.Models.Recruiter", b =>
                {
                    b.Navigation("JobRequests");

                    b.Navigation("ProjectRequests");
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
