// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForge.Data;

#nullable disable

namespace SkillForge.API.Migrations
{
    [DbContext(typeof(SkillForgeDbContext))]
    [Migration("20260904140000_AddEmailAuditLogsTable")]
    partial class AddEmailAuditLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperienceInt")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidateId");

                    b.HasIndex("Location");

                    b.HasIndex("PrimaryRole");

                    b.HasIndex("Seniority");

                    b.HasIndex("Availability");

                    b.HasIndex("UserId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateResume", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ResumeId");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateResumes");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateShortlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContactRevealed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyJobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchExplanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectHiringRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CompanyJobRequestId");

                    b.HasIndex("ProjectHiringRequestId");

                    b.ToTable("CandidateShortlists");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyCareer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareersUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScrapeSupported")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("CompanyCareers");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamBreakdownJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TeamBreakdownApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.ToTable("CompanyJobRequests");
                });

            modelBuilder.Entity("SkillForge.Models.EmailAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyJobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectHiringRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CompanyJobRequestId");

                    b.HasIndex("ProjectHiringRequestId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("SentAt");

                    b.ToTable("EmailAuditLogs");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("Title");

                    b.HasIndex("Location");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SkillForge.Models.JobFetchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobFetchHistories");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.Property<int>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobSkillId");

                    b.HasIndex("JobId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamBreakdownJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TeamBreakdownApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.ToTable("ProjectHiringRequests");
                });

            modelBuilder.Entity("SkillForge.Models.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.HasOne("SkillForge.Models.User", null)
                        .WithMany("Candidates")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateResume", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", null)
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateId");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateShortlist", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("SkillForge.Models.CompanyJobRequest", "CompanyJobRequest")
                        .WithMany("Shortlist")
                        .HasForeignKey("CompanyJobRequestId");

                    b.HasOne("SkillForge.Models.ProjectHiringRequest", "ProjectHiringRequest")
                        .WithMany("Shortlist")
                        .HasForeignKey("ProjectHiringRequestId");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", null)
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.HasOne("SkillForge.Models.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId");
                });

            modelBuilder.Entity("SkillForge.Models.EmailAuditLog", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("SkillForge.Models.CompanyJobRequest", "CompanyJobRequest")
                        .WithMany()
                        .HasForeignKey("CompanyJobRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkillForge.Models.ProjectHiringRequest", "ProjectHiringRequest")
                        .WithMany()
                        .HasForeignKey("ProjectHiringRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkillForge.Models.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", null)
                        .WithMany("JobMatches")
                        .HasForeignKey("CandidateId");

                    b.HasOne("SkillForge.Models.Job", null)
                        .WithMany("JobMatches")
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Job", null)
                        .WithMany("Skills")
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.HasOne("SkillForge.Models.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId");
                });

            modelBuilder.Entity("SkillForge.Models.Recruiter", b =>
                {
                    b.HasOne("SkillForge.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillForge.Models.CompanyJobRequest", b =>
                {
                    b.Navigation("Shortlist");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillForge.Models.ProjectHiringRequest", b =>
                {
                    b.Navigation("Shortlist");
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
