// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForge.Data;

#nullable disable

namespace SkillForge.Migrations
{
    [DbContext(typeof(SkillForgeDbContext))]
    [Migration("20260904120000_ExpandCandidateProfileWithRichData")]
    partial class ExpandCandidateProfileWithRichData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredWorkMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperienceInt")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidateId");

                    b.HasIndex("ActiveResumeId");
                    b.HasIndex("Availability");
                    b.HasIndex("Location");
                    b.HasIndex("PrimaryRole");
                    b.HasIndex("Seniority");

                    b.ToTable("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
