// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForge.Data;

#nullable disable

namespace SkillForge.API.Migrations
{
    [DbContext(typeof(SkillForgeDbContext))]
    [Migration("20260712070143_AddIncrementalFetchHistoryAndCurrencyFields")]
    partial class AddIncrementalFetchHistoryAndCurrencyFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateId");

                    b.HasIndex("UserId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced C# Developer",
                            FetchedAtUtc = new DateTime(2026, 7, 12, 7, 1, 41, 806, DateTimeKind.Utc).AddTicks(5187),
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "C# Developer"
                        },
                        new
                        {
                            JobId = 2,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced React Developer",
                            FetchedAtUtc = new DateTime(2026, 7, 12, 7, 1, 41, 807, DateTimeKind.Utc).AddTicks(923),
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "React Developer"
                        },
                        new
                        {
                            JobId = 3,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced DevOps Engineer",
                            FetchedAtUtc = new DateTime(2026, 7, 12, 7, 1, 41, 807, DateTimeKind.Utc).AddTicks(998),
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            JobId = 4,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced Data Engineer",
                            FetchedAtUtc = new DateTime(2026, 7, 12, 7, 1, 41, 807, DateTimeKind.Utc).AddTicks(1061),
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "Data Engineer"
                        },
                        new
                        {
                            JobId = 5,
                            ApplyUrl = "",
                            Benefits = "",
                            CompanyName = "SkillForge Inc",
                            Country = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Looking for an experienced Full Stack Developer",
                            FetchedAtUtc = new DateTime(2026, 7, 12, 7, 1, 41, 807, DateTimeKind.Utc).AddTicks(1122),
                            Location = "Remote",
                            SalaryRange = "50000-120000",
                            Title = "Full Stack Developer"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.JobFetchHistory", b =>
                {
                    b.Property<int>("JobFetchHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSuccessfulFetchUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobFetchHistoryId");

                    b.ToTable("JobFetchHistories");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 12,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 13,
                            IsRequired = true,
                            JobId = 1,
                            ProficiencyLevel = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 21,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 22,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            Id = 23,
                            IsRequired = true,
                            JobId = 2,
                            ProficiencyLevel = 4,
                            SkillName = "CSS"
                        },
                        new
                        {
                            Id = 31,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = 32,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Kubernetes"
                        },
                        new
                        {
                            Id = 33,
                            IsRequired = true,
                            JobId = 3,
                            ProficiencyLevel = 4,
                            SkillName = "Azure"
                        },
                        new
                        {
                            Id = 41,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "Python"
                        },
                        new
                        {
                            Id = 42,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 43,
                            IsRequired = true,
                            JobId = 4,
                            ProficiencyLevel = 4,
                            SkillName = "Spark"
                        },
                        new
                        {
                            Id = 51,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 52,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 53,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 54,
                            IsRequired = true,
                            JobId = 5,
                            ProficiencyLevel = 4,
                            SkillName = "Azure"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@skillforge.com",
                            PasswordHash = "$2a$11$6r2wEZVCp9v4EL0vPVA8uu7eYQ/qk4jZvJAqEYkLvyTlL6YsH8pf2",
                            Role = "Recruiter",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.HasOne("SkillForge.Models.User", "User")
                        .WithMany("Candidates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillForge.Models.CandidateSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SkillForge.Models.JobMatch", b =>
                {
                    b.HasOne("SkillForge.Models.Candidate", "Candidate")
                        .WithMany("JobMatches")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillForge.Models.Job", "Job")
                        .WithMany("Matches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillForge.Models.JobSkill", b =>
                {
                    b.HasOne("SkillForge.Models.Job", "Job")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillForge.Models.Candidate", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillForge.Models.Job", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("SkillForge.Models.User", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
